import type { App } from 'vue'
import zhCn from 'element-plus/es/locale/lang/zh-cn'

import {
  ElButton,
  ElForm,
  ElFormItem,
  ElInput,
  ElInputNumber,
  ElAutocomplete,
  ElSelect,
  ElOption,
  ElOptionGroup,
  ElTable,
  ElTableColumn,
  ElPagination,
  ElDialog,
  ElCard,
  ElRow,
  ElCol,
  ElTag,
  ElMessage,
  ElMessageBox,
  ElLoading,
  ElNotification,
  ElIcon,
  ElUpload,
  ElDropdown,
  ElDropdownMenu,
  ElDropdownItem,
  ElMenu,
  ElMenuItem,
  ElSubMenu,
  ElTabs,
  ElTabPane,
  ElBadge,
  ElAvatar,
  ElSkeleton,
  ElDivider,
  ElLink,
  ElCheckbox,
  ElCheckboxGroup,
  ElRadio,
  ElRadioGroup,
  ElRadioButton,
  ElSwitch,
  ElDatePicker,
  ElTimePicker,
  ElTimeSelect,
  ElTooltip,
  ElPopover,
  ElAlert,
  ElImage,
  ElDescriptions,
  ElDescriptionsItem,
  ElEmpty,
  ElProgress,
  ElTree,
  ElTreeSelect,
  ElCascader,
  ElColorPicker,
  ElTransfer,
  ElSlider,
  ElRate,
  ElCarousel,
  ElCarouselItem,
  ElCollapse,
  ElCollapseItem,
  ElTimeline,
  ElTimelineItem,
  ElResult,
  ElStatistic,
  ElCountdown,
  ElConfigProvider,
  ElContainer,
  ElHeader,
  ElAside,
  ElMain,
  ElFooter,
  ElBacktop,
  ElAffix,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElPageHeader,
  ElSteps,
  ElStep,
  ElDrawer,
  ElPopconfirm,
  ElSkeletonItem,
  ElSpace
} from 'element-plus'

import {
  Edit,
  Delete,
  Search,
  Refresh,
  Plus,
  Download,
  Upload,
  Setting,
  User,
  Document,
  Menu,
  Close,
  Check,
  Warning,
  InfoFilled,
  SuccessFilled,
  CircleCheck,
  CircleClose,
  ArrowDown,
  ArrowUp,
  ArrowLeft,
  ArrowRight,
  Loading,
  More,
  MoreFilled,
  Phone,
  PhoneFilled,
  Location,
  LocationFilled,
  Calendar,
  Clock,
  View,
  Hide,
  Star,
  StarFilled,
  Key,
  Message,
  Bell,
  BellFilled,
  Connection,
  CopyDocument,
  Picture,
  RefreshLeft
} from '@element-plus/icons-vue'

const components: Record<string, any> = {
  ElButton,
  ElForm,
  ElFormItem,
  ElInput,
  ElInputNumber,
  ElAutocomplete,
  ElSelect,
  ElOption,
  ElOptionGroup,
  ElTable,
  ElTableColumn,
  ElPagination,
  ElDialog,
  ElCard,
  ElRow,
  ElCol,
  ElTag,
  ElIcon,
  ElUpload,
  ElDropdown,
  ElDropdownMenu,
  ElDropdownItem,
  ElMenu,
  ElMenuItem,
  ElSubMenu,
  ElTabs,
  ElTabPane,
  ElBadge,
  ElAvatar,
  ElSkeleton,
  ElDivider,
  ElLink,
  ElCheckbox,
  ElCheckboxGroup,
  ElRadio,
  ElRadioGroup,
  ElRadioButton,
  ElSwitch,
  ElDatePicker,
  ElTimePicker,
  ElTimeSelect,
  ElTooltip,
  ElPopover,
  ElAlert,
  ElImage,
  ElDescriptions,
  ElDescriptionsItem,
  ElEmpty,
  ElProgress,
  ElTree,
  ElTreeSelect,
  ElCascader,
  ElColorPicker,
  ElTransfer,
  ElSlider,
  ElRate,
  ElCarousel,
  ElCarouselItem,
  ElCollapse,
  ElCollapseItem,
  ElTimeline,
  ElTimelineItem,
  ElResult,
  ElStatistic,
  ElCountdown,
  ElConfigProvider,
  ElContainer,
  ElHeader,
  ElAside,
  ElMain,
  ElFooter,
  ElBacktop,
  ElAffix,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElPageHeader,
  ElSteps,
  ElStep,
  ElDrawer,
  ElPopconfirm,
  ElSkeletonItem,
  ElSpace
}

const icons: Record<string, any> = {
  Edit,
  Delete,
  Search,
  Refresh,
  Plus,
  Download,
  Upload,
  Setting,
  User,
  Document,
  Menu,
  Close,
  Check,
  Warning,
  InfoFilled,
  SuccessFilled,
  CircleCheck,
  CircleClose,
  ArrowDown,
  ArrowUp,
  ArrowLeft,
  ArrowRight,
  Loading,
  More,
  MoreFilled,
  Phone,
  PhoneFilled,
  Location,
  LocationFilled,
  Calendar,
  Clock,
  View,
  Hide,
  Star,
  StarFilled,
  Key,
  Message,
  Bell,
  BellFilled,
  Connection,
  CopyDocument,
  Picture,
  RefreshLeft
}

export const setupElementPlus = (app: App<Element>) => {
  Object.entries(components).forEach(([name, component]) => {
    app.component(name, component)
  })

  Object.entries(icons).forEach(([name, component]) => {
    app.component(name, component)
  })

  app.config.globalProperties.$message = ElMessage
  app.config.globalProperties.$messageBox = ElMessageBox
  app.config.globalProperties.$loading = ElLoading.service
  app.config.globalProperties.$notify = ElNotification

  app.directive('loading', ElLoading.directive)
}

export { ElMessage, ElMessageBox, ElLoading, ElNotification }
